/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./inertia/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./inertia/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./inertia/components/ui/alert/AlertTitle.vue')['default']
    AppHead: typeof import('./inertia/components/ui/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Card: typeof import('./inertia/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./inertia/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./inertia/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./inertia/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./inertia/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./inertia/components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./inertia/components/ui/checkbox/Checkbox.vue')['default']
    Drawer: typeof import('./inertia/components/ui/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./inertia/components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./inertia/components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./inertia/components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./inertia/components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./inertia/components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./inertia/components/ui/drawer/DrawerTitle.vue')['default']
    DropdownMenu: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Sonner: typeof import('./inertia/components/ui/sonner/Sonner.vue')['default']
    Textarea: typeof import('./inertia/components/ui/textarea/Textarea.vue')['default']
    ToastManager: typeof import('./inertia/components/ui/ToastManager.vue')['default']
  }
}
